name = "admin-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
 

[[d1_databases]]
binding = "DB"
database_name = "noesys-dev"
database_id = "83331df4-d437-4c67-92e4-313065a15762"

[env.development]
routes = [
  { pattern = "api.localhost/admin/*", zone_name = "localhost" }
]

[vars]
ENVIRONMENT = "production"

[env.production]
routes = [
  { pattern = "api.example.com/admin/*", zone_name = "example.com" }
]
